#!/bin/bash
set -e

TG_TOKEN=
TG_CHAT_ID=

torsocks curl -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
	-d chat_id=$TG_CHAT_ID \
	-d text="${timestamp}"$'\n'"${phone_number}"$'\n'"${message}"
